# Generated by Django 3.0 on 2022-05-26 00:58

from django.db import migrations


def transfer_profiles(apps, schema_editor):
    OldProfiles = apps.get_model('oc_lettings_site', 'Profile')
    NewProfiles = apps.get_model('profiles', 'Profile')

    NewProfiles.objects.bulk_create(NewProfiles(
        user=old_object.user, favorite_city=old_object.favorite_city)
        for old_object in OldProfiles.objects.all())


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_profiles, migrations.RunPython.noop)
    ]
