# Generated by Django 3.0 on 2022-05-26 00:22

from django.db import migrations


def transfer_lettings(apps, schema_editor):
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    NewLetting = apps.get_model('lettings', 'Letting')
    NewAddress = apps.get_model('lettings', 'Address')

    dict_fields = ('number', 'street', 'city', 'state', 'zip_code',
                   'country_iso_code')

    objects = list()

    for letting in OldLetting.objects.all():
        old_title = letting.title
        old_address = letting.address

        address_dict = {k: getattr(old_address, k , None) for k in dict_fields}
        address = NewAddress.objects.create(**address_dict)

        objects.append(NewLetting(title=old_title, address=address))

    NewLetting.objects.bulk_create(objects)


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_lettings, migrations.RunPython.noop)
    ]
