version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: python:3.8-slim-buster
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Linting
          command: flake8
  container:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run: docker build -t ${DOCKERHUB_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
      - run: docker push ${DOCKERHUB_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}


workflows:
    build-test-and-deploy:
      jobs:
        - build-and-test
        - container:
            requires:
              - build-and-test
            filters:
              branches:
                only:
                  - main
        - heroku/deploy-via-git:
            requires:
              - container
            filters:
              branches:
                only:
                  - main
